# see https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml

theme: jekyll-theme-minimal

title: Daniel Philippus

# avatar: "/path/to/avatar.png"
# round-avatar: false

# navbar-links:

social-network-links:
  linkedin: daniel-philippus
  
share-links-active:
  linkedin: true
  
 
